### ISSUE TITLE
Add support for variable placeholders in Manifests (compliment to values placeholders)

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus#67]
**Brief Description of the Enhancement**

Extend the feature of supporting values in manifests and support for variable substitution based on prior processed manifests (implied dependency, in this case)

**Describe the benefit of this proposed enhancement**

Allows the implementation of some manifests that set some variable values to re-use those values in other manifests.

**Code examples, pseudo code or any other technical description of the proposal**

General parsing rule:

* The final result must be a `str` type value. Therefore, if the following conversions should be done:
    * For values of type `dict` or `list`: convert to a string with the JSON representation
    * For encoded strings, decode the string
    * For `int` or `Decimal` values, convert to string
    * For other objects, call the `__str__` method (use `str(value)`)
    * `None` will be converted to an empty string
* If the variable is not found, the final result will be an empty string

Basic example:

```yaml
---
kind: ShellScript
version: v1
metadata:
  name: cli-get-aws-secret-sandbox
  skipDeleteAll: true
  environments:
  - sandbox
spec:
  source:
    type: filePath
    path: '/opt/get-aws-sandbox-secret.sh'
---
kind: AwsBoto3Session
version: v1
metadata:
  name: aws-boto3-session-v1-aws-session-access-key-sandbox
  dependencies:
    apply: cli-get-aws-secret-sandbox
  environments:
  - sandbox
  executeOnlyOnceOnApply: true
  skipDeleteAll: true
spec:
  awsAccessKeyId: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  awsRegion: eu-central-1
  awsSecretAccessKey:
    source: '{{ .Variables.ShellScript:cli-get-aws-secret-sandbox:sandbox:STDOUT }}'
```
