### ISSUE TITLE
Variable substitution must have newline removed

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus#74]
**Describe the bug**

Variable substitution must have the newline removed if present. Other white space should remain intact.

**To Reproduce**

```yaml
---
kind: ShellScript
version: v1
metadata:
  name: test1
  skipDeleteAll: true
  skipApplyAll: true 
spec:
  source:
    type: inline
    value: echo "Hello "
---
kind: ShellScript
version: v1
metadata:
  name: test2
  dependencies:
    apply:
    - test1
spec:
  source:
    type: inline
    value: echo "{{ .Variables.ShellScript:test1:default:STDOUT }} world!" > /tmp/test.txt
```

Run:

```shell
/path/to/animus apply -m $PWD/example.yaml -s /path/to/py-animus-extensions/implementations
```

Expected in `/tmp/test.txt`:

```text
Hello world!
```

Actual result:

```text
Hello
 world!
```

**Expected behavior**

The newline should be strip from the value

**Development Environment (please complete the following information):**

 - OS: Linux
 - Python Version: 3x
 - py-animus: 1.0.12

**Additional context**

n/a
