### ISSUE TITLE
Support parsing YAML with custom Tags (like AWS CloudFormation)

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus#78]
**Brief Description of the Enhancement**

Currently, YAML with custom tags fails to parse to JSON objects.

**Describe the benefit of this proposed enhancement**

Able to properly serialize and de-serialize YAML containing custom tags to JSON/Strings/Dicts

**Code examples, pseudo code or any other technical description of the proposal**

Example from [AWS Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html):

```yaml
---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  RootDomainName:
    Type: String
    Default: example.tld

Resources:

  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'My hosted zone'
      Name: !Ref RootDomainName
```
